# Simple test for manual B/Omega benchmark
快速验证 `cd_A` / `cd_B` / `cd_BOmega` 三个算法是否可在人工场景上正常运行。

In [7]:
import os
import sys
import argparse

cwd = os.getcwd()
repo_root = cwd if os.path.basename(cwd) != 'experiments' else os.path.abspath('..')
if repo_root not in sys.path:
    sys.path.append(repo_root)

from experiments.test_manual_B_Omega_cd_algorithms import (
    get_manual_experiments,
    run_one_experiment,
    save_trial_csv,
    save_summary_csv,
)

In [8]:
args = argparse.Namespace(
    n_repeats=20,
    seed=0,
    data_seed=42,
    threshold=0.05,
    k=None,
    dag_tol=1e-8,
    epochs_a=500,
    epochs_b=500,
    epochs_bomega=500,
    lambda_l0=0.0,
    tol=1e-4,
    patience=10,
    min_epochs=100,
    eps_omega=1e-8,
    outdir=os.path.join('experiments', 'results'),
    tag='manual_B_Omega_cd_simple_test',
)

experiments = get_manual_experiments()
for exp in experiments:
    print(f'Experiment: {exp["name"]}')
    rows = run_one_experiment(exp, n_samples=10000, args=args)
    print(f'rows generated: {len(rows)}\n')

Experiment: d=3, A→B←C
========================================================================================
Running: d=3, A→B←C
cd_A       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.337s
cd_B       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.255s
cd_BOmega  Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.286s
rows generated: 60

Experiment: d=3, A→B→C
========================================================================================
Running: d=3, A→B→C
cd_A       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.343s
cd_B       Correct rate=0.550 | CPDAG_SHD=0.45 | Time=0.258s
cd_BOmega  Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.301s
rows generated: 60

Experiment: d=3, A→B→C + A→C
========================================================================================
Running: d=3, A→B→C + A→C
cd_A       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.290s
cd_B       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.224s
cd_BOmega  Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.259s
rows generated: 60

Experiment: d=4, A→B, B→C, B→D
========================================================================================
Running: d=4, A→B, B→C, B→D
cd_A       Correct rate=0.500 | CPDAG_SHD=1.00 | Time=0.597s
cd_B       Correct rate=0.200 | CPDAG_SHD=1.60 | Time=0.464s
cd_BOmega  Correct rate=0.350 | CPDAG_SHD=1.15 | Time=0.487s
rows generated: 60

Experiment: d=4, A→C, A→D, B→C, B→D
========================================================================================
Running: d=4, A→C, A→D, B→C, B→D
cd_A       Correct rate=0.800 | CPDAG_SHD=1.20 | Time=0.498s
cd_B       Correct rate=0.650 | CPDAG_SHD=2.10 | Time=0.379s
cd_BOmega  Correct rate=0.750 | CPDAG_SHD=1.50 | Time=0.426s
rows generated: 60

Experiment: d=4, A→D, B→D, C→D
========================================================================================
Running: d=4, A→D, B→D, C→D
cd_A       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.540s
cd_B       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.419s
cd_BOmega  Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.461s
rows generated: 60

Experiment: d=5, e=4, |v|=0
========================================================================================
Running: d=5, e=4, |v|=0
cd_A       Correct rate=0.500 | CPDAG_SHD=1.45 | Time=0.905s
cd_B       Correct rate=0.200 | CPDAG_SHD=2.35 | Time=0.729s
cd_BOmega  Correct rate=0.500 | CPDAG_SHD=1.30 | Time=0.811s
rows generated: 60

Experiment: d=5, e=4, |v|=1
========================================================================================
Running: d=5, e=4, |v|=1
DAG/k constraint, continue
cd_A       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.912s
cd_B       Correct rate=0.900 | CPDAG_SHD=0.40 | Time=0.682s
cd_BOmega  Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.758s
rows generated: 60

Experiment: d=5, e=4, |v|=2
========================================================================================
Running: d=5, e=4, |v|=2
cd_A       Correct rate=0.900 | CPDAG_SHD=0.10 | Time=0.854s
cd_B       Correct rate=0.700 | CPDAG_SHD=1.20 | Time=0.676s
cd_BOmega  Correct rate=0.900 | CPDAG_SHD=0.10 | Time=0.739s
rows generated: 60

In [10]:
import pandas as pd

all_rows = []

for exp in experiments:
    exp_rows = run_one_experiment(exp, n_samples=10000, args=args)
    all_rows.extend(exp_rows)

# 明细表
results_df = pd.DataFrame([row.__dict__ for row in all_rows])
results_df = results_df.sort_values(["experiment", "algorithm", "repeat_id"]).reset_index(drop=True)

# 汇总表（每个实验 × 每个算法）
summary_df = (
    results_df
    .groupby(["experiment", "algorithm"], as_index=False)
    .agg(
        repeats=("repeat_id", "count"),
        mec_rate=("mec_match", "mean"),
        exact_rate=("exact_match", "mean"),
        cpdag_shd_mean=("cpdag_shd", "mean"),
        cpdag_shd_std=("cpdag_shd", "std"),
        runtime_mean_sec=("runtime_sec", "mean"),
        runtime_std_sec=("runtime_sec", "std"),
    )
    .sort_values(["experiment", "algorithm"])
    .reset_index(drop=True)
)

summary_df[["mec_rate", "exact_rate", "cpdag_shd_mean", "cpdag_shd_std", "runtime_mean_sec", "runtime_std_sec"]] = (
    summary_df[["mec_rate", "exact_rate", "cpdag_shd_mean", "cpdag_shd_std", "runtime_mean_sec", "runtime_std_sec"]].round(4)
)

print(f"Total rows: {len(results_df)}")
print("\nDetail table (first 20 rows):")
display(results_df.head(20))

print("\nSummary table:")
display(summary_df)

========================================================================================
Running: d=3, A→B←C
cd_A       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.270s
cd_B       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.209s
cd_BOmega  Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.242s
========================================================================================
Running: d=3, A→B→C
cd_A       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.293s
cd_B       Correct rate=0.550 | CPDAG_SHD=0.45 | Time=0.239s
cd_BOmega  Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.275s
========================================================================================
Running: d=3, A→B→C + A→C
cd_A       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.304s
cd_B       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.252s
cd_BOmega  Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.281s
========================================================================================
Running: d=4, A→B, B→C, B→D
cd_A       Correct rate=0.500 | CPDAG_SHD=1.00 | Time=0.657s
cd_B       Correct rate=0.200 | CPDAG_SHD=1.60 | Time=0.538s
cd_BOmega  Correct rate=0.350 | CPDAG_SHD=1.15 | Time=0.569s
========================================================================================
Running: d=4, A→C, A→D, B→C, B→D
cd_A       Correct rate=0.800 | CPDAG_SHD=1.20 | Time=0.498s
cd_B       Correct rate=0.650 | CPDAG_SHD=2.10 | Time=0.352s
cd_BOmega  Correct rate=0.750 | CPDAG_SHD=1.50 | Time=0.383s
========================================================================================
Running: d=4, A→D, B→D, C→D
cd_A       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.488s
cd_B       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.397s
cd_BOmega  Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.468s
========================================================================================
Running: d=5, e=4, |v|=0
cd_A       Correct rate=0.500 | CPDAG_SHD=1.45 | Time=0.879s
cd_B       Correct rate=0.200 | CPDAG_SHD=2.35 | Time=0.710s
cd_BOmega  Correct rate=0.500 | CPDAG_SHD=1.30 | Time=0.791s
========================================================================================
Running: d=5, e=4, |v|=1
DAG/k constraint, continue
cd_A       Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.990s
cd_B       Correct rate=0.900 | CPDAG_SHD=0.40 | Time=0.768s
cd_BOmega  Correct rate=1.000 | CPDAG_SHD=0.00 | Time=0.851s
========================================================================================
Running: d=5, e=4, |v|=2
cd_A       Correct rate=0.900 | CPDAG_SHD=0.10 | Time=1.171s
cd_B       Correct rate=0.700 | CPDAG_SHD=1.20 | Time=0.927s
cd_BOmega  Correct rate=0.900 | CPDAG_SHD=0.10 | Time=1.002s
Total rows: 540

Detail table (first 20 rows):

,n_samples,experiment,algorithm,repeat_id,seed,mec_match,exact_match,cpdag_shd,runtime_sec
0,10000,"d=3, A→B←C",cd_A,0,0,1,1,0.0,0.285593
1,10000,"d=3, A→B←C",cd_A,1,1,1,1,0.0,0.261947
2,10000,"d=3, A→B←C",cd_A,2,2,1,1,0.0,0.301665
3,10000,"d=3, A→B←C",cd_A,3,3,1,1,0.0,0.247169
4,10000,"d=3, A→B←C",cd_A,4,4,1,1,0.0,0.253172
5,10000,"d=3, A→B←C",cd_A,5,5,1,1,0.0,0.279413
6,10000,"d=3, A→B←C",cd_A,6,6,1,1,0.0,0.264977
7,10000,"d=3, A→B←C",cd_A,7,7,1,1,0.0,0.266373
8,10000,"d=3, A→B←C",cd_A,8,8,1,1,0.0,0.268348
9,10000,"d=3, A→B←C",cd_A,9,9,1,1,0.0,0.265293
10,10000,"d=3, A→B←C",cd_A,10,10,1,1,0.0,0.264687
11,10000,"d=3, A→B←C",cd_A,11,11,1,1,0.0,0.271920
12,10000,"d=3, A→B←C",cd_A,12,12,1,1,0.0,0.260109
13,10000,"d=3, A→B←C",cd_A,13,13,1,1,0.0,0.269897
14,10000,"d=3, A→B←C",cd_A,14,14,1,1,0.0,0.274630
15,10000,"d=3, A→B←C",cd_A,15,15,1,1,0.0,0.248548
16,10000,"d=3, A→B←C",cd_A,16,16,1,1,0.0,0.267513
17,10000,"d=3, A→B←C",cd_A,17,17,1,1,0.0,0.312717
18,10000,"d=3, A→B←C",cd_A,18,18,1,1,0.0,0.268191
19,10000,"d=3, A→B←C",cd_A,19,19,1,1,0.0,0.263972

Summary table:

,experiment,algorithm,repeats,mec_rate,exact_rate,cpdag_shd_mean,cpdag_shd_std,runtime_mean_sec,runtime_std_sec
0,"d=3, A→B←C",cd_A,20,1.00,1.00,0.00,0.0000,0.2698,0.0158
1,"d=3, A→B←C",cd_B,20,1.00,1.00,0.00,0.0000,0.2090,0.0093
2,"d=3, A→B←C",cd_BOmega,20,1.00,1.00,0.00,0.0000,0.2424,0.0103
3,"d=3, A→B→C",cd_A,20,1.00,0.75,0.00,0.0000,0.2935,0.0187
4,"d=3, A→B→C",cd_B,20,0.55,0.30,0.45,0.5104,0.2391,0.0326
5,"d=3, A→B→C",cd_BOmega,20,1.00,0.75,0.00,0.0000,0.2753,0.0230
6,"d=3, A→B→C + A→C",cd_A,20,1.00,0.75,0.00,0.0000,0.3043,0.0158
7,"d=3, A→B→C + A→C",cd_B,20,1.00,0.70,0.00,0.0000,0.2525,0.0218
8,"d=3, A→B→C + A→C",cd_BOmega,20,1.00,1.00,0.00,0.0000,0.2813,0.0167
9,"d=4, A→B, B→C, B→D",cd_A,20,0.50,0.30,1.00,1.4142,0.6568,0.0970
10,"d=4, A→B, B→C, B→D",cd_B,20,0.20,0.05,1.60,1.5009,0.5384,0.1078
11,"d=4, A→B, B→C, B→D",cd_BOmega,20,0.35,0.25,1.15,1.3485,0.5691,0.0562
12,"d=4, A→C, A→D, B→C, B→D",cd_A,20,0.80,0.80,1.20,2.4623,0.4979,0.1747
13,"d=4, A→C, A→D, B→C, B→D",cd_B,20,0.65,0.65,2.10,2.9362,0.3520,0.0992
14,"d=4, A→C, A→D, B→C, B→D",cd_BOmega,20,0.75,0.75,1.50,2.6656,0.3829,0.1100
15,"d=4, A→D, B→D, C→D",cd_A,20,1.00,1.00,0.00,0.0000,0.4879,0.0818
16,"d=4, A→D, B→D, C→D",cd_B,20,1.00,1.00,0.00,0.0000,0.3971,0.0648
17,"d=4, A→D, B→D, C→D",cd_BOmega,20,1.00,1.00,0.00,0.0000,0.4680,0.0853
18,"d=5, e=4, |v|=0",cd_A,20,0.50,0.35,1.45,2.0125,0.8785,0.0697
19,"d=5, e=4, |v|=0",cd_B,20,0.20,0.15,2.35,1.9270,0.7097,0.0647
20,"d=5, e=4, |v|=0",cd_BOmega,20,0.50,0.35,1.30,1.9494,0.7914,0.0671
21,"d=5, e=4, |v|=1",cd_A,20,1.00,1.00,0.00,0.0000,0.9904,0.1130
22,"d=5, e=4, |v|=1",cd_B,20,0.90,0.55,0.40,1.2312,0.7678,0.0688
23,"d=5, e=4, |v|=1",cd_BOmega,20,1.00,1.00,0.00,0.0000,0.8506,0.1070
24,"d=5, e=4, |v|=2",cd_A,20,0.90,0.90,0.10,0.3078,1.1708,0.0806
25,"d=5, e=4, |v|=2",cd_B,20,0.70,0.70,1.20,2.5257,0.9267,0.0716
26,"d=5, e=4, |v|=2",cd_BOmega,20,0.90,0.90,0.10,0.3078,1.0016,0.0617

In [11]:
# 简洁版矩阵表：横轴=9个实验，纵轴=算法，值=mec_rate
mec_matrix = (
    summary_df
    .pivot(index='algorithm', columns='experiment', values='mec_rate')
)

# 若列名中包含“d=...”，按数字维度顺序稳定排序；否则保持原顺序
mec_matrix = mec_matrix.reindex(sorted(mec_matrix.columns), axis=1)

print('MEC rate matrix (rows=algorithm, cols=experiment):')
display(mec_matrix.round(4))

MEC rate matrix (rows=algorithm, cols=experiment):

experiment,"d=3, A→B←C","d=3, A→B→C","d=3, A→B→C + A→C","d=4, A→B, B→C, B→D","d=4, A→C, A→D, B→C, B→D","d=4, A→D, B→D, C→D","d=5, e=4, |v|=0","d=5, e=4, |v|=1","d=5, e=4, |v|=2"
algorithm,,,,,,,,,
cd_A,1.0,1.00,1.0,0.50,0.80,1.0,0.5,1.0,0.9
cd_B,1.0,0.55,1.0,0.20,0.65,1.0,0.2,0.9,0.7
cd_BOmega,1.0,1.00,1.0,0.35,0.75,1.0,0.5,1.0,0.9